
import React from 'react';
import { motion } from 'framer-motion';
import { ShieldCheck, FileText, ChevronLeft } from 'lucide-react';
import { useNavigate } from 'react-router-dom';
import ThreeOrb from '../components/ThreeOrb';
import Footer from '../components/Footer';
import SEO from '../components/SEO';

const TermsAndConditions: React.FC = () => {
  const navigate = useNavigate();

  return (
    <div className="min-h-screen bg-[#050505] text-white selection:bg-premium-accent selection:text-black overflow-x-hidden pt-32 transition-colors duration-300">
      <SEO 
        title="Terms and Conditions" 
        description="Official terms of use and legal documentation for Shriya's Coaching Platform." 
      />
      <ThreeOrb className="absolute top-0 right-0 w-[500px] h-[500px] opacity-10 pointer-events-none -translate-y-1/4" color="#C5A059" />
      
      <div className="max-w-4xl mx-auto px-6 relative z-10 pb-24">
        <button 
          onClick={() => navigate(-1)}
          className="flex items-center gap-2 text-white/40 hover:text-white transition-colors mb-12 group"
        >
          <ChevronLeft size={16} className="group-hover:-translate-x-1 transition-transform" />
          <span className="text-[10px] font-black uppercase tracking-[0.3em]">Back to Experience</span>
        </button>

        <div className="mb-20">
            <motion.div 
                initial={{ opacity: 0, y: 20 }} 
                animate={{ opacity: 1, y: 0 }} 
                className="flex items-center gap-4 mb-6"
            >
                <div className="p-3 bg-premium-accent/10 rounded-xl text-premium-accent">
                    <ShieldCheck size={28} />
                </div>
                <h1 className="text-4xl md:text-6xl font-light serif-font uppercase luxury-text-gradient">Terms of Use.</h1>
            </motion.div>
            <p className="text-xs text-white/30 uppercase tracking-[0.4em] font-black">Last Updated: October 2023</p>
        </div>

        <motion.div 
            initial={{ opacity: 0 }} 
            animate={{ opacity: 1 }} 
            transition={{ delay: 0.2 }}
            className="space-y-10 text-white/70 leading-relaxed font-light text-sm md:text-base"
        >
            <section className="space-y-4">
                <p>
                    This document is an electronic record in terms of Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.
                </p>
                <p>
                    This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy and Terms of Use for access or usage of domain name <span className="text-premium-accent">https://shriyasgurukul.in/</span> ('Website'), including the related mobile site and mobile application (hereinafter referred to as 'Platform').
                </p>
                <p>
                    The Platform is owned by <span className="font-bold text-white uppercase tracking-wider">Shriya Tejani</span>, a company incorporated under the Companies Act, 1956 with its registered office at AHMEDABAD, Ahmedabad, India (hereinafter referred to as 'Platform Owner', 'we', 'us', 'our').
                </p>
            </section>

            <section className="p-8 bg-white/[0.02] border border-white/5 rounded-[32px] space-y-4">
                <h2 className="text-xl font-bold text-white serif-font italic">Binding Obligations</h2>
                <p>
                    Your use of the Platform and services and tools are governed by the following terms and conditions (“Terms of Use”) as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with the Platform Owner and these terms and conditions including the policies constitute Your binding obligations, with Platform Owner.
                </p>
                <p>
                    These Terms of Use relate to your use of our website, goods (as applicable) or services (as applicable) (collectively, 'Services'). Any terms and conditions proposed by You which are in addition to or which conflict with these Terms of Use are expressly rejected by the Platform Owner and shall be of no force or effect. These Terms of Use can be modified at any time without assigning any reason. It is your responsibility to periodically review these Terms of Use to stay informed of updates.
                </p>
            </section>

            <section className="space-y-6">
                <h3 className="text-[10px] font-black uppercase tracking-[0.4em] text-white/30 border-b border-white/10 pb-2">Institutional Protocol</h3>
                <ul className="space-y-6 list-none">
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">01.</span>
                        <p>To access and use the Services, you agree to provide true, accurate and complete information to us during and after registration, and you shall be responsible for all acts done through the use of your registered account on the Platform.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">02.</span>
                        <p>Neither we nor any third parties provide any warranty or guarantee as to the accuracy, timeliness, performance, completeness or suitability of the information and materials offered on this website or through the Services, for any specific purpose. You acknowledge that such information and materials may contain inaccuracies or errors and we expressly exclude liability for any such inaccuracies or errors to the fullest extent permitted by law.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">03.</span>
                        <p>Your use of our Services and the Platform is solely and entirely at your own risk and discretion for which we shall not be liable to you in any manner. You are required to independently assess and ensure that the Services meet your requirements.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">04.</span>
                        <p>The contents of the Platform and the Services are proprietary to us and are licensed to us. You will not have any authority to claim any intellectual property rights, title, or interest in its contents. The contents includes and is not limited to the design, layout, look and graphics.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">05.</span>
                        <p>You acknowledge that unauthorized use of the Platform and/or the Services may lead to action against you as per these Terms of Use and/or applicable laws.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">06.</span>
                        <p>You agree to pay us the charges associated with availing the Services.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">07.</span>
                        <p>You agree not to use the Platform and/ or Services for any purpose that is unlawful, illegal or forbidden by these Terms, or Indian or local laws that might apply to you.</p>
                    </li>
                    <li className="flex gap-4">
                        <span className="text-premium-accent font-black">08.</span>
                        <p>You agree and acknowledge that website and the Services may contain links to other third party websites. On accessing these links, you will be governed by the terms of use, privacy policy and such other policies of such third party websites. These links are provided for your convenience for provide further information.</p>
                    </li>
                </ul>
            </section>

            <section className="p-8 border border-white/5 rounded-[32px] space-y-4">
                <h2 className="text-xl font-bold text-white serif-font italic">Indemnity & Liability</h2>
                <p>
                    You shall indemnify and hold harmless Platform Owner, its affiliates, group companies (as applicable) and their respective officers, directors, agents, and employees, from any claim or demand, or actions including reasonable attorney's fees, made by any third party or penalty imposed due to or arising out of Your breach of this Terms of Use, privacy Policy and other Policies, or Your violation of any law, rules or regulations or the rights (including infringement of intellectual property rights) of a third party.
                </p>
                <p>
                    Notwithstanding anything contained in these Terms of Use, the parties shall not be liable for any failure to perform an obligation under these Terms if performance is prevented or delayed by a force majeure event.
                </p>
            </section>

            <section className="space-y-4">
                <h2 className="text-xl font-bold text-white serif-font italic">Jurisdiction</h2>
                <p>
                    These Terms and any dispute or claim relating to it, or its enforceability, shall be governed by and construed in accordance with the laws of India. All disputes arising out of or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts in <span className="text-white font-bold">Ahmedabad and Gujarat</span>.
                </p>
            </section>

            <section className="pt-10 border-t border-white/10">
                <p className="text-white/40 text-xs font-bold uppercase tracking-widest mb-4">Contact Information</p>
                <div className="flex flex-col gap-2">
                    <span className="text-lg serif-font text-premium-accent">admin@advedasolutions.in</span>
                </div>
            </section>
        </motion.div>
      </div>

      <Footer />
    </div>
  );
};

export default TermsAndConditions;
